export const GET_TODO_ITEMS = 'GET_TODO_ITEMS';
export const GET_TODO_ITEMS_SUCCESS = 'GET_TODO_ITEMS_SUCCESS';
export const GET_TODO_ITEMS_FAILURE = 'GET_TODO_ITEMS_FAILURE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const REQUEST_ERROR = 'SET_ERROR';
