export const GET_TODO_ITEMS = "GET_TODO_ITEMS";
export const GET_TODO_ITEMS_SUCCESS = "GET_TODO_ITEMS_SUCCESS";
export const CREATE_TODO_ITEM = "CREATE_TODO_ITEM";
export const CREATE_TODO_ITEM_SUCCESS = "CREATE_TODO_ITEM_SUCCESS";
export const UPDATE_TODO_ITEM = "UPDATE_TODO_ITEM";
export const UPDATE_TODO_ITEM_SUCCESS = "UPDATE_TODO_ITEM_SUCCESS";
export const GET_TODO_ITEM = "GET_TODO_ITEM";
export const GET_TODO_ITEM_SUCCESS = "GET_TODO_ITE_SUCCESS";

export const REQUEST_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
